# Configuração de conexão com o MySQL.
# Ajuste estes valores para o seu ambiente (NÃO é necessário recompilar o projeto).
db.url=jdbc:mysql://localhost:3306/oghamdb?useSSL=false&serverTimezone=UTC
db.user=root
db.password=1888
